;;; limen-context-tests.el --- Typed context tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'dired)
(require 'ert)
(require 'limen-herdr)
(require 'seq)

(defun limen-context-tests--event (name)
  "Return registered event descriptor named NAME."
  (seq-find (lambda (event) (equal (alist-get 'name event) name))
            (limen-events)))

(defun limen-context-tests--occurrences (needle text)
  "Count non-overlapping occurrences of NEEDLE in TEXT."
  (let ((start 0)
        (count 0))
    (while (string-match (regexp-quote needle) text start)
      (setq start (match-end 0)
            count (1+ count)))
    count))

(defun limen-context-tests--sorted-names (names)
  "Return NAMES as a sorted list of strings."
  (sort (mapcar (lambda (name)
                  (if (symbolp name) (symbol-name name) name))
                (append names nil))
        #'string<))

(defun limen-context-tests--object-keys (object)
  "Return OBJECT's JSON member names in sorted order."
  (limen-context-tests--sorted-names (mapcar #'car object)))

(ert-deftest limen-context-push-schema-validates-recursive-file-items ()
  (let* ((descriptor (limen-context-tests--event "context.push"))
         (schema (alist-get 'payload_schema descriptor))
         (properties (alist-get 'properties schema))
         (items-schema (alist-get 'items properties))
         (item-schema (alist-get 'items items-schema))
         (item-properties (alist-get 'properties item-schema))
         (primary '((path . "/project/first.el") (line . 1) (column . 0)))
         (valid-items
          [((type . "file") (path . "/project/first.el"))
           ((type . "file") (path . "/project/second.el")
            (line . 3) (column . 2) (end_line . 4) (end_column . 1)
            (text . "selected"))])
         (session (limen-open-session :provider 'test)))
    (unwind-protect
        (progn
          (should (equal (alist-get 'type items-schema) "array"))
          (should (equal (alist-get 'type item-schema) "object"))
          (should (eq (alist-get 'additionalProperties item-schema)
                      :json-false))
          (should (equal (limen-context-tests--sorted-names
                          (alist-get 'required item-schema))
                         '("path" "type")))
          (should (equal (limen-context-tests--object-keys item-properties)
                         '("column" "end_column" "end_line" "line"
                           "path" "text" "type")))
          (should (equal (alist-get 'enum (alist-get 'type item-properties))
                         ["file"]))
          (dolist (field '((path . "string") (line . "integer")
                           (column . "integer") (end_line . "integer")
                           (end_column . "integer") (text . "string")))
            (should (equal (alist-get 'type
                                      (alist-get (car field) item-properties))
                           (cdr field))))
          (should (equal (limen-context-tests--sorted-names
                          (alist-get 'required schema))
                         '("column" "line" "path")))
          (should (limen-session-publish
                   session "context.push"
                   (append primary `((items . ,valid-items)))))
          (dolist (invalid
                   '([((type . "directory") (path . "/project/first.el"))]
                     [((type . "file") (path . 7))]
                     [((type . "file") (path . "/project/first.el")
                       (unexpected . t))]))
            (ert-info ((format "invalid nested items=%S" invalid))
              (should-error
               (limen-session-publish
                session "context.push" (append primary `((items . ,invalid))))
               :type 'limen-invalid-arguments))))
      (unless (limen-session-closed-p session)
        (limen-close-session session)))))

(ert-deftest limen-herdr-excerpt-draws-the-sent-lines-and-marks-the-point ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "(defun alpha ()\n  \"Doc.\"\n  (beta))\n\n(defun gamma ()\n  nil)\n")
    (goto-char (point-min))
    (forward-line 2)
    (forward-char 3)
    (let* ((limen-herdr-context-window 1)
           (context '((path . "/tmp/project/alpha.el")
                      (line . 3) (column . 2) (end_line . 3) (end_column . 9)))
           (excerpt (limen-herdr--excerpt context 3 3)))
      (should (equal (split-string excerpt "\n")
                     '("  ╭─[alpha.el:3:3]"
                       "2 │   \"Doc.\""
                       "3 ┃   (beta))"
                       "  ·    ▲ point"
                       "4 │ "
                       "  ╰─")))
      (let ((limen-herdr-context-window 0))
        (should-not (limen-herdr--excerpt context 3 3))))
    (let* ((limen-herdr-context-window 10)
           (context '((buffer . "*scratch*")
                      (line . 1) (column . 0) (end_line . 3) (end_column . 9)))
           (rows (split-string (limen-herdr--excerpt context 1 0) "\n")))
      (should (equal (nth 0 rows) "  ╭─[*scratch*:1:0]"))
      (should (equal (nth 1 rows) "1 ┃ (defun alpha ()"))
      (should (equal (nth 2 rows) "  · ▲ point"))
      (should (equal (nth 4 rows) "3 ┃   (beta))"))
      (should (equal (car (last rows)) "  ╰─")))))

(ert-deftest limen-herdr-context-names-what-only-the-editor-knows ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "(defun alpha ()\n  (beta))\n")
    (goto-char (point-min))
    (forward-line 1)
    (forward-char 3)
    (let* ((state (limen-herdr--point-state
                   '((line . 2) (column . 2) (end_line . 2) (end_column . 9))))
           (context (append '((buffer . "alpha.el") (line . 2) (column . 2)
                              (end_line . 2) (end_column . 9))
                            state))
           (fields (limen-herdr--context-fields context nil)))
      (should (equal (alist-get 'major_mode state) "emacs-lisp-mode"))
      (should (equal (alist-get 'point_line state) 2))
      (should (equal (alist-get 'point_column state) 3))
      (should (member "mode: emacs-lisp-mode" fields))
      (should (member "symbol: beta" fields))
      (should (member "defun: alpha" fields)))))

(ert-deftest limen-herdr-diagnostics-line-names-severity-place-and-message ()
  (let ((context '((diagnostics . [((severity . "error") (line . 12) (column . 4)
                                    (message . "unbalanced parens\nsecond line"))
                                   ((severity . "warning") (line . 13) (column . 0)
                                    (message . "unused"))]))))
    (should (equal (limen-herdr--diagnostics-text context)
                   (concat "diagnostics: error at 12:4 unbalanced parens; "
                           "warning at 13:0 unused"))))
  (should-not (limen-herdr--diagnostics-text '((diagnostics . [])))))

(ert-deftest limen-herdr-send-context-carries-a-file-outside-the-project ()
  (let* ((root (file-truename (make-temp-file "limen-context-root" t)))
         (outside-root (file-truename
                        (make-temp-file "limen-context-outside" t)))
         (outside (expand-file-name "outside.el" outside-root))
         (denied (expand-file-name "denied.el" root))
         (integration (limen-open-session :provider 'pi :project-root root))
         (state (make-limen-herdr-state :provider 'pi :session integration))
         (entry '((server_key . "/s") (terminal_id . "t")))
         (limen-project-path-deny-regexps '("\\`denied\\.el\\'"))
         drafts buffers)
    (unwind-protect
        (progn
          (with-temp-file outside (insert "outside\n"))
          (with-temp-file denied (insert "secret\n"))
          (cl-letf (((symbol-function 'herdr-agent-resolve-session)
                     (lambda (_target) 'agent))
                    ((symbol-function 'herdr-agent-session-p)
                     (lambda (_session) t))
                    ((symbol-function 'herdr-agent-session-adapter-state)
                     (lambda (_session) state)))
            (let ((limen-herdr-context-hook
                   (list (lambda (_session context _root text)
                           (push (cons context text) drafts)))))
              (with-current-buffer (find-file-noselect outside)
                (push (current-buffer) buffers)
                (let ((transient-mark-mode t))
                  (goto-char (point-min))
                  (set-mark (point))
                  (end-of-line)
                  (setq mark-active t)
                  (let ((text (limen-herdr-send-context entry)))
                    (should (stringp text))
                    (should (string-match-p
                             (regexp-quote (format "file: %s:1:0-1:7" outside))
                             text))
                    (should (string-match-p "1 ┃ outside" text))
                    (should (string-match-p "· +▲ point" text))
                    (should (equal (cdar drafts) text))
                    (should (equal (alist-get 'text (caar drafts)) "outside")))))
              (with-current-buffer (find-file-noselect denied)
                (push (current-buffer) buffers)
                (should-not (limen-herdr-send-context entry))
                (should (= (length drafts) 1))))))
      (dolist (buffer buffers)
        (when (buffer-live-p buffer)
          (set-buffer-modified-p nil)
          (kill-buffer buffer)))
      (unless (limen-session-closed-p integration)
        (limen-close-session integration))
      (delete-directory root t)
      (delete-directory outside-root t))))

(ert-deftest limen-herdr-dired-push-is-atomic-and-routed-when-unclaimed ()
  (let* ((root (file-truename (make-temp-file "limen-context-root" t)))
         (outside-root (file-truename
                        (make-temp-file "limen-context-outside" t)))
         (first (expand-file-name "first.el" root))
         (second (expand-file-name "second.el" root))
         (denied (expand-file-name "denied.el" root))
         (unreadable (expand-file-name "unreadable.el" root))
         (directory (expand-file-name "directory" root))
         (symlink (expand-file-name "linked.el" root))
         (outside (expand-file-name "outside.el" outside-root))
         (cap-files nil)
         (integration (limen-open-session :provider 'pi :project-root root))
         (state (make-limen-herdr-state :provider 'pi :session integration))
         (agent (make-symbol "agent"))
         (real-selection (make-symbol "real-selection"))
         (selected nil)
         (dired-calls nil)
         (published nil)
         (limen-herdr-push-functions
          (list (lambda (_session context _root) (push context published) nil)))
         (dired-payload nil)
         (prompts nil)
         (events nil)
         (dired-buffer nil)
         (original-readable-p (symbol-function 'file-readable-p))
         (original-dired-get-marked-files
          (symbol-function 'dired-get-marked-files)))
    (unwind-protect
        (progn
          (with-temp-file first (insert "COPIED-FIRST-CONTENT"))
          (with-temp-file second (insert "COPIED-SECOND-CONTENT"))
          (dolist (file (list denied unreadable))
            (with-temp-file file (insert "not context")))
          (make-directory directory)
          (make-symbolic-link first symlink)
          (with-temp-file outside (insert "outside"))
          (dotimes (index 101)
            (let ((file (expand-file-name (format "cap-%03d.el" index) root)))
              (with-temp-file file (insert "cap"))
              (push file cap-files)))
          (setq cap-files (nreverse cap-files)
                dired-buffer (dired-noselect root))
          (cl-letf (((symbol-function 'herdr-agent-session-p)
                     (lambda (candidate) (eq candidate agent)))
                    ((symbol-function 'herdr-agent-session-adapter-state)
                     (lambda (_session) state))
                    ((symbol-function 'herdr-agent-session-server)
                     (lambda (_session) "/tmp/herdr.sock"))
                    ((symbol-function 'herdr-agent-session-terminal)
                     (lambda (_session) "term-push"))
                    ((symbol-function 'dired-get-marked-files)
                     (lambda (&optional localp arg &rest extra)
                       (push (list localp arg extra) dired-calls)
                       (if (eq selected real-selection)
                           (apply original-dired-get-marked-files
                                  localp arg extra)
                         selected)))
                    ((symbol-function 'file-readable-p)
                     (lambda (file)
                       (and (not (file-equal-p file unreadable))
                            (funcall original-readable-p file))))
                    ((symbol-function 'herdr-agent-prompt)
                     (lambda (target text)
                       (push (list target text) prompts)))
                    ((symbol-function 'limen-session-publish)
                     (lambda (session event payload)
                       (should (eq session integration))
                       (push (list event payload) events))))
            (with-current-buffer dired-buffer
              (setq selected (list first second))
              (should (limen-herdr-push-context agent))
              (should (= (length published) 1))
              (should (= (length prompts) 1))
              (setq dired-payload (car published))
              (let* ((payload dired-payload)
                     (items (append (alist-get 'items payload) nil))
                     (serialized (prin1-to-string payload)))
                (should (equal (alist-get 'path payload) first))
                (should (= (alist-get 'line payload) 1))
                (should (= (alist-get 'column payload) 0))
                (should-not (assq 'text payload))
                (should (equal (mapcar (lambda (item)
                                        (list (alist-get 'type item)
                                              (alist-get 'path item)))
                                      items)
                               `(("file" ,first) ("file" ,second))))
                (dolist (item items)
                  (should (equal (alist-get 'type item) "file"))
                  (should (stringp (alist-get 'path item)))
                  (should-not (assq 'text item)))
                (should-not (string-match-p "COPIED-FIRST-CONTENT" serialized))
                (should-not (string-match-p "COPIED-SECOND-CONTENT" serialized)))

              (setq published nil prompts nil
                    selected (list second first))
              (setf (limen-herdr-state-provider state) 'codex)
              (should (limen-herdr-push-context agent))
              (should (= (length published) 1))
              (should (= (length prompts) 1))
              (let ((text (cadar prompts)))
                (should (= (limen-context-tests--occurrences "second.el" text) 1))
                (should (= (limen-context-tests--occurrences "first.el" text) 1))
                (should-not (string-match-p (regexp-quote root) text))
                (should (< (string-match "second\\.el" text)
                           (string-match "first\\.el" text)))
                (should-not (string-match-p "COPIED-FIRST-CONTENT" text))
                (should-not (string-match-p "COPIED-SECOND-CONTENT" text)))

              (setf (limen-herdr-state-provider state) 'pi
                    (limen-herdr-state-route state)
                    (make-limen-mcp-route :id "route" :token "t"
                                          :session integration))
              (setq prompts nil published nil
                    selected (list first second))
              (should (limen-herdr-push-context agent))
              (should (= (length published) 1))
              (should-not prompts)
              (should (equal (caar events) "context.push"))
              (should (equal (alist-get 'path (cadar events)) first))
              (setf (limen-herdr-state-route state) nil)

              (setq prompts nil published nil events nil)
              (dired-unmark-all-marks)
              (should (dired-goto-file first))
              (should (equal (dired-get-filename nil t) first))
              (setq selected real-selection)
              (should-error (limen-herdr-push-context agent)
                            :type 'user-error)
              (should-not published)
              (should-not prompts)

              (dolist (case
                       `((directory (,first ,directory) nil)
                         (symlink (,first ,symlink) nil)
                         (unreadable (,first ,unreadable) nil)
                         (outside (,first ,outside) nil)
                         (denied (,first ,denied) ("\\`denied\\.el\\'"))
                         (item-cap ,cap-files nil)))
                (pcase-let ((`(,label ,files ,deny-regexps) case))
                  (setq selected files)
                  (let ((limen-project-path-deny-regexps deny-regexps))
                    (ert-info ((format "invalid Dired selection=%s" label))
                      (should-error (limen-herdr-push-context agent)
                                    :type 'user-error)))
                  (should-not published)
                  (should-not prompts)))
              (should (= (length dired-calls) 10))
              (dolist (call dired-calls)
                (should (equal call '(nil marked nil)))))))
      (when (buffer-live-p dired-buffer)
        (kill-buffer dired-buffer))
      (unless (limen-session-closed-p integration)
        (limen-close-session integration))
      (delete-directory root t)
      (delete-directory outside-root t))))

(provide 'limen-context-tests)
;;; limen-context-tests.el ends here
