;;; limen-inbox-tests.el --- Inbox tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'limen-inbox)

(defvar herdr-status-sections-functions)

(defun limen-inbox-tests--payload (event &rest fields)
  (append fields
          `((hook_event_name . ,event) (session_id . "agent-1")
            (server . "/tmp/alpha.sock") (pane . "%1"))))

(defconst limen-inbox-tests--claude-input
  '((questions . [((question . "Which database?") (header . "Database")
                   (options . [((label . "PostgreSQL") (description . "strong"))
                               ((label . "MongoDB"))])
                   (multiSelect . :false))
                  ((question . "Include tests?") (header . "Scope")
                   (options . [((label . "Yes")) ((label . "No"))])
                   (multiSelect . t))])))

(defconst limen-inbox-tests--codex-input
  '((questions . [((id . "q1") (question . "Which cache?") (header . "Cache")
                   (options . [((label . "Redis")) ((label . "Memory"))])
                   (isOther . t) (isSecret . :false))])))

(defmacro limen-inbox-tests--with-inbox (&rest body)
  (declare (indent 0) (debug t))
  `(let ((limen-inbox--questions nil)
         (refreshes 0))
     (cl-letf (((symbol-function 'herdr-status-request-refresh)
                (lambda () (cl-incf refreshes))))
       ,@body)))

(defun limen-inbox-tests--event (event &rest fields)
  (limen-inbox--on-event "claude" (apply #'limen-inbox-tests--payload event fields)
                         nil nil))

(ert-deftest limen-inbox-tracks-questions-from-ask-to-answer ()
  (limen-inbox-tests--with-inbox
    (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                              '(tool_use_id . "t1")
                              (cons 'tool_input limen-inbox-tests--claude-input))
    (should (= refreshes 1))
    (let ((entry (car (limen-inbox-questions))))
      (should (equal (alist-get 'id entry) "t1"))
      (should (equal (alist-get 'agent_session entry) "agent-1"))
      (should (equal (alist-get 'server entry) (file-truename "/tmp/alpha.sock")))
      (should (equal (alist-get 'pane entry) "%1"))
      (should (equal (mapcar (lambda (question)
                               (list (alist-get 'header question)
                                     (alist-get 'question question)
                                     (alist-get 'options question)
                                     (alist-get 'multi question)
                                     (alist-get 'other question)))
                             (alist-get 'questions entry))
                     '(("Database" "Which database?" ("PostgreSQL" "MongoDB") nil nil)
                       ("Scope" "Include tests?" ("Yes" "No") t nil)))))
    (limen-inbox--on-event "codex"
                           (limen-inbox-tests--payload
                            "PreToolUse" '(session_id . "agent-2")
                            '(tool_name . "request_user_input") '(tool_use_id . "c1")
                            (cons 'tool_input limen-inbox-tests--codex-input))
                           nil nil)
    (should (= (length (limen-inbox-questions)) 2))
    (should (equal (alist-get 'other (car (alist-get 'questions
                                                     (cadr (limen-inbox-questions)))))
                   t))
    (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                              '(tool_use_id . "t1")
                              (cons 'tool_input limen-inbox-tests--codex-input))
    (should (= (length (limen-inbox-questions)) 2))
    (should (equal (mapcar (lambda (entry) (alist-get 'id entry))
                           (limen-inbox-questions))
                   '("c1" "t1")))
    (limen-inbox-tests--event "PreToolUse" '(tool_name . "Bash")
                              '(tool_use_id . "b1")
                              '(tool_input . ((command . "ls"))))
    (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                              '(tool_use_id . "t2")
                              '(tool_input . ((questions . []))))
    (limen-inbox-tests--event "PostToolUse" '(tool_name . "Bash") '(tool_use_id . "b1"))
    (limen-inbox-tests--event "PostToolUse" '(tool_name . "AskUserQuestion")
                              '(tool_use_id . "unknown"))
    (should (= (length (limen-inbox-questions)) 2))
    (should (= refreshes 3))
    (limen-inbox-tests--event "PostToolUse" '(tool_name . "AskUserQuestion")
                              '(tool_use_id . "t1"))
    (should (equal (mapcar (lambda (entry) (alist-get 'id entry))
                           (limen-inbox-questions))
                   '("c1")))
    (should (= refreshes 4))
    (limen-inbox-tests--event "Stop")
    (should (= (length (limen-inbox-questions)) 1))
    (limen-inbox-tests--event "Stop" '(session_id . "agent-2"))
    (should-not (limen-inbox-questions))
    (should (= refreshes 5))
    (dolist (event '("UserPromptSubmit" "SessionEnd" "PostToolUse"))
      (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                                '(tool_use_id . "again")
                                (cons 'tool_input limen-inbox-tests--claude-input))
      (limen-inbox-tests--event event '(tool_name . "AskUserQuestion"))
      (should-not (limen-inbox-questions)))
    (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                              (cons 'tool_input limen-inbox-tests--claude-input))
    (should (string-prefix-p "agent-1:" (alist-get 'id (car (limen-inbox-questions)))))
    (limen-inbox-clear)
    (should-not (limen-inbox-questions))))

(ert-deftest limen-inbox-groups-questions-by-dashboard-agent-and-prunes-the-rest ()
  (limen-inbox-tests--with-inbox
    (let ((alpha `((server_key . "/tmp/alpha.sock") (pane_id . "%1") (name . "api")))
          (beta `((server_key . "/tmp/alpha.sock") (pane_id . "%2") (name . "docs"))))
      (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                                '(tool_use_id . "t1")
                                (cons 'tool_input limen-inbox-tests--claude-input))
      (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                                '(tool_use_id . "t2") '(pane . "%9")
                                (cons 'tool_input limen-inbox-tests--codex-input))
      (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                                '(tool_use_id . "t3") '(pane . "%1")
                                (cons 'tool_input limen-inbox-tests--codex-input))
      (limen-inbox-tests--event "PreToolUse" '(tool_name . "AskUserQuestion")
                                '(tool_use_id . "t4") '(pane . "")
                                (cons 'tool_input limen-inbox-tests--codex-input))
      (let ((groups (limen-inbox--groups (list alpha beta))))
        (should (= (length groups) 1))
        (should (eq (caar groups) alpha))
        (should (equal (mapcar (lambda (question) (alist-get 'header question))
                               (cdar groups))
                       '("Database" "Scope" "Cache"))))
      (should (equal (mapcar (lambda (entry) (alist-get 'id entry))
                             (limen-inbox-questions))
                     '("t1" "t3")))
      (should-not (limen-inbox--groups (list beta)))
      (should-not (limen-inbox-questions)))))

(ert-deftest limen-inbox-mode-registers-events-and-completes-installs ()
  (let* ((directory (make-temp-file "limen-inbox-settings" t))
         (process-environment
          (append (list (concat "CLAUDE_CONFIG_DIR=" directory)
                        (concat "CODEX_HOME=" (expand-file-name "codex" directory)))
                  process-environment))
         (limen-hooks-command "limen")
         (limen-hooks-extra-events nil)
         (limen-hooks-event-functions nil)
         (herdr-status-sections-functions nil)
         (limen-inbox--questions nil))
    (unwind-protect
        (progn
          (limen-inbox-mode -1)
          (limen-hooks-install 'claude)
          (should (equal (mapcar #'car (limen-hooks-events))
                         '("UserPromptSubmit" "SessionStart")))
          (limen-inbox-mode 1)
          (should (equal (mapcar #'car (limen-hooks-events))
                         '("UserPromptSubmit" "SessionStart" "PreToolUse"
                           "PostToolUse" "Stop" "SessionEnd")))
          (should (memq #'limen-inbox--on-event limen-hooks-event-functions))
          (should (memq #'limen-inbox--insert-section
                        herdr-status-sections-functions))
          (should (limen-hooks-installed-p 'claude))
          (should-not (limen-hooks-any-installed-p 'codex))
          (limen-inbox-mode -1)
          (should (equal (mapcar #'car (limen-hooks-events))
                         '("UserPromptSubmit" "SessionStart")))
          (should-not (memq #'limen-inbox--on-event limen-hooks-event-functions))
          (should (limen-hooks-installed-p 'claude))
          (should-not (limen-hooks--event-installed-p
                       (limen-hooks--read-settings
                        (limen-hooks-settings-file 'claude))
                       "PreToolUse" 'claude)))
      (limen-inbox-mode -1)
      (delete-directory directory t))))

(provide 'limen-inbox-tests)
;;; limen-inbox-tests.el ends here
