;;; limen-herdr-tests.el --- Herdr integration tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'limen-herdr)

(defvar herdr-agent-name-function)
(defvar herdr-agent-title-function)

(ert-deftest limen-herdr-project-settings-choose-model-and-effort-at-launch ()
  (let ((limen-herdr-project-settings
         '(("/repo/" :harness "codex" :model "gpt-6" :effort "high")
           ("/repo/sub/" :model "deep")))
        (provider 'codex)
        (project "/repo/.worktrees/x"))
    (cl-letf (((symbol-function 'limen-herdr--provider) (lambda (_session) provider))
              ((symbol-function 'limen-herdr-state) #'ignore)
              ((symbol-function 'herdr-agent-session-project) (lambda (_session) project)))
      (should (equal (limen-herdr--settings-arguments 'session)
                     '("-c" "model=\"gpt-6\"" "-c" "model_reasoning_effort=\"high\"")))
      (setq provider 'claude)
      (should-not (limen-herdr--settings-arguments 'session))
      (setq project "/repo/sub/x")
      (should (equal (limen-herdr--settings-arguments 'session) '("--model" "deep")))
      (let ((limen-herdr-launch-settings '(:harness "claude" :effort "low")))
        (should (equal (limen-herdr--settings-arguments 'session) '("--effort" "low"))))
      (should (equal (limen-herdr--arguments 'session '("go"))
                     '("--model" "deep" "go"))))))

(ert-deftest limen-herdr-project-settings-round-trip-through-the-menu ()
  (let ((settings '(:harness "pi" :effort "high")))
    (should (equal (limen-herdr-settings-arguments settings)
                   '("--harness=pi" "--effort=high")))
    (should (equal (limen-herdr-arguments-settings
                    (limen-herdr-settings-arguments settings))
                   settings))))

(ert-deftest limen-herdr-agent-name-asks-claude-about-the-conversation-and-its-peers ()
  (let ((entry '((agent . "claude") (cwd . "/repo/limen/.worktrees/naming/")
                 (agent_session . ((value . "s1")))
                 (terminal_title_stripped . "Injectable agent name derivation")))
        asked)
    (cl-letf (((symbol-function 'herdr-entry-directory)
               (lambda (entry) (alist-get 'cwd entry)))
              ((symbol-function 'herdr-agent--repository) (lambda (_) "/repo/limen/"))
              ((symbol-function 'limen-herdr--opening-request)
               (lambda (id) (and (equal id "s1") "Make agent names injectable")))
              ((symbol-function 'limen-herdr--recent-messages)
               (lambda (id) (and (equal id "s1")
                                 '(("user" . "Name agents from their talk")
                                   ("assistant" . "Reading memex now")))))
              ((symbol-function 'limen-herdr--other-agents)
               (lambda (_) '("Memex Popup Window" "Cmw Migrations")))
              ((symbol-function 'limen-herdr--ask-name)
               (lambda (description) (setq asked description) "Limen Agent Naming")))
      (should (equal (limen-herdr-agent-name entry) "Limen Agent Naming"))
      (should (equal asked (concat "<agent>\nrepository: limen\nharness: claude\n"
                                   "terminal title: Injectable agent name derivation\n</agent>\n\n"
                                   "<opening_request>\nMake agent names injectable\n</opening_request>\n\n"
                                   "<recent_turns>\nuser: Name agents from their talk\n\n"
                                   "assistant: Reading memex now\n</recent_turns>\n\n"
                                   "<names_taken>\nMemex Popup Window\nCmw Migrations\n</names_taken>\n\n"
                                   "Name the agent described above."))))))

(ert-deftest limen-herdr-opening-request-is-the-session-s-first-question ()
  (cl-letf (((symbol-function 'limen-herdr--memex)
             (lambda (&rest _)
               '(((record . ((role . "assistant") (text . "hello"))))
                 ((record . ((role . "user") (text . "  "))))
                 ((record . ((role . "user") (text . "Could hooks block Emacs?"))))
                 ((record . ((role . "user") (text . "later"))))))))
    (should (equal (limen-herdr--opening-request "s1") "Could hooks block Emacs?"))
    (should-not (limen-herdr--opening-request nil))))

(ert-deftest limen-herdr-recent-messages-read-the-last-turns-each-side-once ()
  (let ((limen-herdr--name-turns 2)
        (limen-herdr--name-message-chars 6)
        calls)
    (cl-letf (((symbol-function 'limen-herdr--memex)
               (lambda (&rest arguments)
                 (push arguments calls)
                 (if (member "--page-info" arguments)
                     '(((record . ((role . "user")))) ((type . "page") (total . 800)))
                   '(((record . ((role . "user") (turn_id . "t1") (text . "old"))))
                     ((record . ((role . "user") (turn_id . "t2") (text . "ask"))))
                     ((record . ((role . "tool_use") (turn_id . "t2") (text . "ls"))))
                     ((record . ((role . "assistant") (turn_id . "t2") (text . "one"))))
                     ((record . ((role . "assistant") (turn_id . "t2") (text . "  "))))
                     ((record . ((role . "assistant") (turn_id . "t2") (text . "two"))))
                     ((record . ((role . "user") (turn_id . "t3") (text . "a long question"))))
                     ((record . ((role . "assistant") (turn_id . "t3") (text . "a long answer"))))
                     ((type . "page")))))))
      (should (equal (limen-herdr--recent-messages "s1")
                     '(("user" . "ask") ("assistant" . "…e\n\ntwo")
                       ("user" . "a long…") ("assistant" . "…answer"))))
      (should (equal (cadr (member "--offset" (car calls))) "300"))
      (should-not (limen-herdr--recent-messages nil)))))

(ert-deftest limen-herdr-other-agents-are-the-rest-of-the-herdr-session ()
  (let ((entry '((name . "own") (pane_id . "%1") (server_key . "/tmp/s.sock")))
        server)
    (cl-letf (((symbol-function 'herdr--entry-server) (lambda (e) (alist-get 'server_key e)))
              ((symbol-function 'herdr-entry-label)
               (lambda (agent) (or (alist-get 'name agent) (alist-get 'title agent))))
              ((symbol-function 'herdr-api-agent-list)
               (lambda ()
                 (setq server herdr-socket-path)
                 '((agents . (((pane_id . "%1") (name . "own"))
                              ((pane_id . "%2") (name . "docs"))
                              ((pane_id . "%3") (title . "Untitled Work"))
                              ((pane_id . "%4") (name . "docs"))))))))
      (should (equal (limen-herdr--other-agents entry) '("docs" "Untitled Work")))
      (should (equal server "/tmp/s.sock")))))

(ert-deftest limen-herdr-agent-name-derives-one-where-claude-gives-none ()
  (let ((titled '((agent . "claude") (terminal_title_stripped . "Index work")))
        (untitled '((agent . "codex"))))
    (cl-letf (((symbol-function 'herdr-entry-directory) #'ignore)
              ((symbol-function 'limen-herdr--recent-messages) #'ignore)
              ((symbol-function 'limen-herdr--other-agents) #'ignore)
              ((symbol-function 'limen-herdr--ask-name) #'ignore)
              ((symbol-function 'herdr-agent-derive-name)
               (lambda (entry) (concat "derived-" (alist-get 'agent entry)))))
      (should (equal (limen-herdr-agent-name titled) "derived-claude"))
      (should (equal (limen-herdr-agent-name untitled) "derived-codex")))))

(ert-deftest limen-herdr-name-answers-only-a-short-title ()
  (should (equal (limen-herdr--name-answer
                  "{\"result\":\"x\",\"structured_output\":{\"name\":\" Emacs Blocking Hooks \"}}")
                 "Emacs Blocking Hooks"))
  (should (equal (limen-herdr--name-answer
                  "{\"structured_output\":{\"name\":\"Buchungskreis Rename Dry Runs\"}}")
                 "Buchungskreis Rename Dry Runs"))
  (should (equal (limen-herdr--name-answer
                  "{\"structured_output\":{\"name\":\"Hooks Blocking the Main Loop\"}}")
                 "Hooks Blocking the Main Loop"))
  (dolist (output '("{\"structured_output\":{\"name\":\"limen-workon-scope\"}}"
                    "{\"structured_output\":{\"name\":\"Limen  Workon\"}}"
                    "{\"structured_output\":{\"name\":\"Extraordinarily Long Title Over Thirty\"}}"
                    "{\"structured_output\":{}}" "{\"result\":\"Emacs Blocking Hooks\"}"
                    "Emacs Blocking Hooks" "" nil))
    (should-not (limen-herdr--name-answer output))))

(ert-deftest limen-herdr-agent-title-reads-a-name-as-words ()
  (should (equal (limen-herdr-agent-title "limen-workon-scope") "Limen Workon Scope"))
  (should (equal (limen-herdr-agent-title "my_agent-2") "My Agent 2"))
  (should (equal (limen-herdr-agent-title "rename-of-the-buchungskreis-to-enfi")
                 "Rename of the Buchungskreis to Enfi"))
  (should (equal (limen-herdr-agent-title "the-state-of-in") "The State of In")))

(ert-deftest limen-herdr-takes-herdr-s-naming-only-where-its-defaults-stand ()
  (let ((herdr-agent-name-function #'herdr-agent-derive-name)
        (herdr-agent-title-function #'upcase))
    (limen-herdr--take-names)
    (should (eq herdr-agent-name-function #'limen-herdr-agent-name))
    (should (eq herdr-agent-title-function #'upcase))
    (limen-herdr--give-back-names)
    (should (eq herdr-agent-name-function #'herdr-agent-derive-name))
    (should (eq herdr-agent-title-function #'upcase))))

(ert-deftest limen-herdr-name-command-uses-the-shared-small-model ()
  (let ((argv (limen-herdr--name-command)))
    (should (equal (cadr (member "--model" argv)) limen-provider-claude-small-model))
    (should (equal (cadr (member "--effort" argv)) "low"))
    (should (equal (cadr (member "--output-format" argv)) "json"))
    (should (= 1 (cl-count "--output-format" argv :test #'equal)))
    (should (equal (cadr (member "--json-schema" argv)) limen-herdr--name-schema))
    (should (equal (car (last argv)) limen-herdr--name-instruction))))

(provide 'limen-herdr-tests)
;;; limen-herdr-tests.el ends here
