;;; limen-herd-tests.el --- Herd notice tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'limen-herd)

(defvar herdr-herd-protocol-functions)
(defvar herdr-herd-sent-functions)
(defvar herdr-agent-event-functions)

(defun limen-herd-tests--entry (name &rest keys)
  "Return a Herdr agent entry called NAME; KEYS may set :status :label :session."
  `((name . ,name) (agent . "claude")
    (agent_status . ,(or (plist-get keys :status) "idle"))
    (agent_session . ((value . ,(or (plist-get keys :session) name))))
    (pane_label . ,(plist-get keys :label))
    (server_key . "/tmp/alpha.sock")
    (terminal_id . ,(concat "term-" name))
    (pane_id . ,(concat "%" name))))

(defun limen-herd-tests--payload (event id &rest fields)
  (append fields `((hook_event_name . ,event) (session_id . ,id)
                   (server . "/tmp/alpha.sock") (pane . ,(concat "%" id)))))

(defmacro limen-herd-tests--with-herd (members &rest body)
  "Run BODY with MEMBERS as the herd `limen' and every Herdr call stubbed.
The sender is the member whose pane the payload names; `prompts' collects
what `herdr-agent-prompt' received as (TARGET . TEXT), newest first, and
`renames' what `limen-herd--rename' received as (PANE . LABEL)."
  (declare (indent 1) (debug (form body)))
  `(let ((limen-herd--prompts (make-hash-table :test #'equal))
         (limen-herd--held (make-hash-table :test #'equal))
         (limen-herd--names (make-hash-table :test #'equal))
         (limen-herd--states (make-hash-table :test #'equal))
         (limen-herd--hooked (make-hash-table :test #'equal))
         (limen-herd--timers (make-hash-table :test #'equal))
         (limen-herd--chatter (make-hash-table :test #'equal))
         (limen-herd-fallback-delay 0)
         (members ,members)
         (prompts nil)
         (renames nil))
     (ignore renames)
     (cl-letf (((symbol-function 'herdr-herd-live-agents) (lambda (&rest _) members))
               ((symbol-function 'limen-herd--recipients)
                (lambda (payload kind &optional self)
                  (when-let* ((self (or self (limen-hooks-agent-for payload members))))
                    (list '("alpha" . "limen") self
                          (seq-filter (lambda (member)
                                        (and (not (eq member self))
                                             (memq kind (limen-herd-subscriptions
                                                         member))))
                                      members)))))
               ((symbol-function 'herdr-herd-notice)
                (lambda (herd text)
                  (format "[herd %s] %s No reply needed." (cdr herd) text)))
               ((symbol-function 'herdr-herd-label-token)
                (lambda (label prefix)
                  (when (and (stringp label)
                             (string-match (concat (regexp-quote prefix)
                                                   "\\([^[:space:]]*\\)")
                                           label))
                    (match-string 1 label))))
               ((symbol-function 'herdr-herd-label-with-token)
                (lambda (_label prefix value) (and value (concat prefix value))))
               ((symbol-function 'herdr-herd--busy-p)
                (lambda (member)
                  (member (alist-get 'agent_status member) '("working" "blocked"))))
               ((symbol-function 'herdr-herd--rename)
                (lambda (entry label)
                  (push (cons (alist-get 'pane_id entry) label) renames)))
               ((symbol-function 'herdr-herd--refresh) #'ignore)
               ((symbol-function 'herdr--entry-target)
                (lambda (entry) (alist-get 'terminal_id entry)))
               ((symbol-function 'herdr-agent-prompt)
                (lambda (target text) (push (cons target text) prompts) text)))
       ,@body)))

(defun limen-herd-tests--event (event id &rest fields)
  (limen-herd--on-event "claude" (apply #'limen-herd-tests--payload event id fields)
                        nil nil))

(ert-deftest limen-herd-subscriptions-round-trip-through-the-label ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen notify:finished,exited wip"))
    (let ((entry (car members)))
      (should (equal '(finished exited) (limen-herd-subscriptions entry)))
      (limen-herd-subscribe (list entry) '(prompt))
      (should (equal '("%a" . "notify:prompt,finished,exited") (car renames)))
      (limen-herd-unsubscribe (list entry) '(finished exited))
      (should (equal '("%a" . nil) (car renames)))
      (limen-herd-toggle (list entry) 'finished)
      (should (equal '("%a" . "notify:exited") (car renames)))
      (limen-herd-toggle (list entry) 'online)
      (should (equal '("%a" . "notify:online,finished,exited") (car renames)))
      (limen-herd-subscribe-defaults (list entry))
      (should (equal '("%a" . "notify:finished,exited") (car renames)))
      (should-not (limen-herd-subscriptions
                   (limen-herd-tests--entry "b" :label "herd:limen notify:bogus"))))))

(ert-deftest limen-herd-finished-notice-reaches-subscribed-idle-peers-and-holds-for-busy ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "b" :label "herd:limen notify:finished")
            (limen-herd-tests--entry "c" :label "herd:limen notify:finished"
                                     :status "working")
            (limen-herd-tests--entry "d" :label "herd:limen"))
    (cl-letf (((symbol-function 'limen-herd--session-name)
               (lambda (&rest _) "limen-3a")))
      (should-not (limen-herd-tests--event
                   "UserPromptSubmit" "a" '(prompt . "fix the tests\nplease")))
      (should-not prompts)
      (limen-herd-tests--event "Stop" "a" '(stop_hook_active . :false)
                               '(last_assistant_message . "All green.\nDetails."))
      (should (equal prompts
                     '(("term-b" . "[herd limen] a finished: \"fix the tests\" (claude session limen-3a). Said: \"All green.\" No reply needed."))))
      (should (equal (limen-herd-tests--event "UserPromptSubmit" "c" '(prompt . "go on"))
                     "[herd limen] a finished: \"fix the tests\" (claude session limen-3a). Said: \"All green.\" No reply needed."))
      (should-not (limen-herd-tests--event "UserPromptSubmit" "c" '(prompt . "more")))
      (should (= (hash-table-count limen-herd--held) 0)))))

(ert-deftest limen-herd-a-busy-peer-is-skipped-when-holding-is-off ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "c" :label "herd:limen notify:finished"
                                     :status "blocked"))
    (let ((limen-herd-hold-for-busy nil))
      (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "task"))
      (limen-herd-tests--event "Stop" "a")
      (should-not prompts)
      (should (= (hash-table-count limen-herd--held) 0)))))

(ert-deftest limen-herd-ignores-chatter-turns ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "b" :label "herd:limen notify:finished,prompt"))
    (limen-herd-tests--event "UserPromptSubmit" "a"
                             '(prompt . "[herd limen] b finished. No reply needed."))
    (limen-herd-tests--event "Stop" "a")
    (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "/herd limen — you are a"))
    (limen-herd-tests--event "Stop" "a")
    (should-not prompts)
    (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "real work"))
    (should (equal (cdr (car prompts))
                   "[herd limen] a started: \"real work\". No reply needed."))
    (limen-herd-tests--event "Stop" "a" '(stop_hook_active . t))
    (should (= (length prompts) 1))
    (limen-herd-tests--event "Stop" "a")
    (should (equal (cdr (car prompts))
                   "[herd limen] a finished: \"real work\". No reply needed."))))

(ert-deftest limen-herd-session-name-comes-from-claude-s-session-files ()
  (let* ((directory (make-temp-file "limen-herd-claude" t))
         (process-environment (cons (concat "CLAUDE_CONFIG_DIR=" directory)
                                    process-environment))
         (limen-herd--names (make-hash-table :test #'equal)))
    (unwind-protect
        (progn
          (make-directory (expand-file-name "sessions" directory))
          (with-temp-file (expand-file-name "sessions/123.json" directory)
            (insert "{\"pid\":123,\"sessionId\":\"s-1\",\"name\":\"limen-3a\",\"nameSource\":\"derived\"}"))
          (with-temp-file (expand-file-name "sessions/124.json" directory)
            (insert "not json"))
          (should (equal (limen-herd--session-name "claude" "s-1") "limen-3a"))
          (should-not (limen-herd--session-name "claude" "s-2"))
          (should-not (limen-herd--session-name "codex" "s-1"))
          (should (equal (limen-herd--session-suffix "claude" "s-1")
                         " (claude session limen-3a)"))
          (should (equal (limen-herd--session-suffix "codex" "s-1") "")))
      (delete-directory directory t))))

(ert-deftest limen-herd-online-and-exit-notices ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "b" :label "herd:limen notify:online,exited"))
    (limen-herd-tests--event "SessionStart" "a" '(source . "compact"))
    (should-not prompts)
    (limen-herd-tests--event "SessionStart" "a" '(source . "resume"))
    (should (equal (cdr (car prompts))
                   "[herd limen] a is online. No reply needed."))
    (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "task"))
    (limen-herd-tests--event "SessionEnd" "a" '(reason . "logout"))
    (should (equal (cdr (car prompts))
                   "[herd limen] a exited (logout). No reply needed."))
    (should (= (hash-table-count limen-herd--prompts) 0))))

(defun limen-herd-tests--observe (pane status)
  (limen-herd--on-herdr-event
   "/tmp/alpha.sock" "pane.updated"
   `((pane . ((pane_id . ,pane) (agent_status . ,status))))))

(ert-deftest limen-herd-herdr-state-changes-make-notices-without-hooks ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "b" :label "herd:limen notify:online,prompt,finished,exited"))
    (limen-herd-tests--observe "%a" "unknown")
    (should-not prompts)
    (limen-herd-tests--observe "%a" "idle")
    (should (equal (cdr (car prompts)) "[herd limen] a is online. No reply needed."))
    (limen-herd-tests--observe "%a" "idle")
    (should (= (length prompts) 1))
    (limen-herd-tests--observe "%a" "working")
    (should (equal (cdr (car prompts)) "[herd limen] a started a turn. No reply needed."))
    (limen-herd-tests--observe "%a" "blocked")
    (should (= (length prompts) 2))
    (limen-herd-tests--observe "%a" "idle")
    (should (equal (cdr (car prompts)) "[herd limen] a finished a turn. No reply needed."))
    (limen-herd--on-herdr-event "/tmp/alpha.sock" "pane.exited" '((pane_id . "%a")))
    (should (equal (cdr (car prompts)) "[herd limen] a exited. No reply needed."))
    (should (= (hash-table-count limen-herd--states) 0))))

(ert-deftest limen-herd-seeding-tells-nobody-about-agents-already-there ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen" :status "working")
            (limen-herd-tests--entry "b" :label "herd:limen notify:online,finished"))
    (limen-herd--seed)
    (should (= (hash-table-count limen-herd--states) 2))
    (limen-herd-tests--observe "%a" "working")
    (should-not prompts)
    (limen-herd-tests--observe "%a" "idle")
    (should (equal (cdr (car prompts)) "[herd limen] a finished a turn. No reply needed."))))

(ert-deftest limen-herd-a-hooked-turn-silences-its-state-change ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "b" :label "herd:limen notify:prompt,finished"))
    (limen-herd--seed)
    (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "task"))
    (limen-herd-tests--observe "%a" "working")
    (limen-herd-tests--event "Stop" "a")
    (limen-herd-tests--observe "%a" "idle")
    (should (equal (mapcar #'cdr prompts)
                   '("[herd limen] a finished: \"task\". No reply needed."
                     "[herd limen] a started: \"task\". No reply needed.")))
    (let ((limen-herd-fallback-delay 5)
          (key (cons (limen-herd--pane-key "/tmp/alpha.sock" "%a") 'prompt)))
      (limen-herd-tests--observe "%a" "working")
      (should (gethash key limen-herd--timers))
      (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "again"))
      (should-not (gethash key limen-herd--timers))
      (should (= (length prompts) 3)))))

(ert-deftest limen-herd-held-notices-flush-when-herdr-sees-the-member-idle ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "a" :label "herd:limen")
            (limen-herd-tests--entry "b" :label "herd:limen notify:prompt,finished")
            (limen-herd-tests--entry "c" :label "herd:limen notify:finished"
                                     :status "working"))
    (limen-herd--seed)
    (limen-herd-tests--event "UserPromptSubmit" "a" '(prompt . "task"))
    (limen-herd-tests--event "Stop" "a")
    (should (= (length prompts) 2))
    (should (gethash "c" limen-herd--held))
    (limen-herd-tests--observe "%c" "idle")
    (should (equal (seq-take prompts 2)
                   '(("term-c" . "[herd limen] a finished: \"task\". No reply needed.")
                     ("term-b" . "[herd limen] c finished a turn. No reply needed."))))
    (should-not (gethash "c" limen-herd--held))
    (limen-herd-tests--observe "%c" "working")
    (limen-herd-tests--observe "%c" "idle")
    (should (= (length prompts) 4))
    (limen-herd-tests--observe "%c" "working")
    (should (equal (cdr (car prompts)) "[herd limen] c started a turn. No reply needed."))
    (limen-herd--on-sent (nth 2 members) "[herd limen] roster")
    (limen-herd-tests--observe "%c" "idle")
    (should (= (length prompts) 5))))

(ert-deftest limen-herd-an-agent-in-no-herd-sends-nothing ()
  (limen-herd-tests--with-herd
      (list (limen-herd-tests--entry "b" :label "herd:limen notify:finished"))
    (limen-herd-tests--event "UserPromptSubmit" "z" '(prompt . "task"))
    (limen-herd-tests--event "Stop" "z")
    (should-not prompts)))

(ert-deftest limen-herd-mode-registers-and-installs ()
  (let ((limen-hooks-extra-events nil)
        (limen-hooks-event-functions nil)
        (herdr-herd-protocol-functions nil)
        (herdr-herd-sent-functions nil)
        (herdr-agent-event-functions nil)
        (limen-hooks--requests nil)
        (limen-hooks--request-timer nil)
        (installed nil)
        (removed nil))
    (cl-letf (((symbol-function 'limen-hooks-request-install)
               (lambda (feature) (push feature installed)))
              ((symbol-function 'limen-hooks-remove-events-everywhere)
               (lambda (events) (setq removed events))))
      (unwind-protect
          (progn
            (limen-herd-mode 1)
            (should (equal limen-hooks-extra-events '(("Stop") ("SessionEnd"))))
            (should (memq #'limen-herd--on-event limen-hooks-event-functions))
            (should (memq #'limen-herd--protocol herdr-herd-protocol-functions))
            (should (memq #'limen-herd--on-sent herdr-herd-sent-functions))
            (should (memq #'limen-herd--on-herdr-event herdr-agent-event-functions))
            (should (equal installed '("herd")))
            (should (string-match-p "notify:finished,exited"
                                    (limen-herd--protocol '("alpha" . "limen"))))
            (limen-herd-mode -1)
            (should-not limen-hooks-extra-events)
            (should-not (memq #'limen-herd--on-event limen-hooks-event-functions))
            (should-not (memq #'limen-herd--protocol herdr-herd-protocol-functions))
            (should-not (memq #'limen-herd--on-herdr-event herdr-agent-event-functions))
            (should (equal removed '("Stop" "SessionEnd"))))
        (limen-herd-mode -1)))))

(provide 'limen-herd-tests)
;;; limen-herd-tests.el ends here
