;;; limen-context-tests.el --- Typed context tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'dired)
(require 'ert)
(require 'limen-claude)
(require 'limen-herdr)
(require 'seq)

(defun limen-context-tests--event (name)
  "Return registered event descriptor named NAME."
  (seq-find (lambda (event) (equal (alist-get 'name event) name))
            (limen-events)))

(defun limen-context-tests--occurrences (needle text)
  "Count non-overlapping occurrences of NEEDLE in TEXT."
  (let ((start 0)
        (count 0))
    (while (string-match (regexp-quote needle) text start)
      (setq start (match-end 0)
            count (1+ count)))
    count))

(defun limen-context-tests--sorted-names (names)
  "Return NAMES as a sorted list of strings."
  (sort (mapcar (lambda (name)
                  (if (symbolp name) (symbol-name name) name))
                (append names nil))
        #'string<))

(defun limen-context-tests--object-keys (object)
  "Return OBJECT's JSON member names in sorted order."
  (limen-context-tests--sorted-names (mapcar #'car object)))

(ert-deftest limen-context-push-schema-validates-recursive-file-items ()
  (let* ((descriptor (limen-context-tests--event "context.push"))
         (schema (alist-get 'payload_schema descriptor))
         (properties (alist-get 'properties schema))
         (items-schema (alist-get 'items properties))
         (item-schema (alist-get 'items items-schema))
         (item-properties (alist-get 'properties item-schema))
         (primary '((path . "/project/first.el") (line . 1) (column . 0)))
         (valid-items
          [((type . "file") (path . "/project/first.el"))
           ((type . "file") (path . "/project/second.el")
            (line . 3) (column . 2) (end_line . 4) (end_column . 1)
            (text . "selected"))])
         (session (limen-open-session :provider 'test)))
    (unwind-protect
        (progn
          (should (equal (alist-get 'type items-schema) "array"))
          (should (equal (alist-get 'type item-schema) "object"))
          (should (eq (alist-get 'additionalProperties item-schema)
                      :json-false))
          (should (equal (limen-context-tests--sorted-names
                          (alist-get 'required item-schema))
                         '("path" "type")))
          (should (equal (limen-context-tests--object-keys item-properties)
                         '("column" "end_column" "end_line" "line"
                           "path" "text" "type")))
          (should (equal (alist-get 'enum (alist-get 'type item-properties))
                         ["file"]))
          (dolist (field '((path . "string") (line . "integer")
                           (column . "integer") (end_line . "integer")
                           (end_column . "integer") (text . "string")))
            (should (equal (alist-get 'type
                                      (alist-get (car field) item-properties))
                           (cdr field))))
          (should (equal (limen-context-tests--sorted-names
                          (alist-get 'required schema))
                         '("column" "line" "path")))
          (should (limen-session-publish
                   session "context.push"
                   (append primary `((items . ,valid-items)))))
          (dolist (invalid
                   '([((type . "directory") (path . "/project/first.el"))]
                     [((type . "file") (path . 7))]
                     [((type . "file") (path . "/project/first.el")
                       (unexpected . t))]))
            (ert-info ((format "invalid nested items=%S" invalid))
              (should-error
               (limen-session-publish
                session "context.push" (append primary `((items . ,invalid))))
               :type 'limen-invalid-arguments))))
      (unless (limen-session-closed-p session)
        (limen-close-session session)))))

(ert-deftest limen-herdr-dired-push-is-atomic-and-provider-compatible ()
  (let* ((root (file-truename (make-temp-file "limen-context-root" t)))
         (outside-root (file-truename
                        (make-temp-file "limen-context-outside" t)))
         (first (expand-file-name "first.el" root))
         (second (expand-file-name "second.el" root))
         (denied (expand-file-name "denied.el" root))
         (unreadable (expand-file-name "unreadable.el" root))
         (directory (expand-file-name "directory" root))
         (symlink (expand-file-name "linked.el" root))
         (outside (expand-file-name "outside.el" outside-root))
         (cap-files nil)
         (integration (limen-open-session :provider 'pi :project-root root))
         (state (make-limen-herdr-state :provider 'pi :session integration))
         (agent (make-symbol "agent"))
         (real-selection (make-symbol "real-selection"))
         (selected nil)
         (dired-calls nil)
         (published nil)
         (dired-payload nil)
         (prompts nil)
         (dired-buffer nil)
         (original-readable-p (symbol-function 'file-readable-p))
         (original-dired-get-marked-files
          (symbol-function 'dired-get-marked-files)))
    (unwind-protect
        (progn
          (with-temp-file first (insert "COPIED-FIRST-CONTENT"))
          (with-temp-file second (insert "COPIED-SECOND-CONTENT"))
          (dolist (file (list denied unreadable))
            (with-temp-file file (insert "not context")))
          (make-directory directory)
          (make-symbolic-link first symlink)
          (with-temp-file outside (insert "outside"))
          (dotimes (index 101)
            (let ((file (expand-file-name (format "cap-%03d.el" index) root)))
              (with-temp-file file (insert "cap"))
              (push file cap-files)))
          (setq cap-files (nreverse cap-files)
                dired-buffer (dired-noselect root))
          (cl-letf (((symbol-function 'herdr-agent-session-p)
                     (lambda (candidate) (eq candidate agent)))
                    ((symbol-function 'herdr-agent-session-adapter-state)
                     (lambda (_session) state))
                    ((symbol-function 'herdr-agent-session-server)
                     (lambda (_session) "/tmp/herdr.sock"))
                    ((symbol-function 'herdr-agent-session-terminal)
                     (lambda (_session) "term-push"))
                    ((symbol-function 'dired-get-marked-files)
                     (lambda (&optional localp arg &rest extra)
                       (push (list localp arg extra) dired-calls)
                       (if (eq selected real-selection)
                           (apply original-dired-get-marked-files
                                  localp arg extra)
                         selected)))
                    ((symbol-function 'file-readable-p)
                     (lambda (file)
                       (and (not (file-equal-p file unreadable))
                            (funcall original-readable-p file))))
                    ((symbol-function 'limen-session-publish)
                     (lambda (session event payload)
                       (should (eq session integration))
                       (should (equal event "context.push"))
                       (push payload published)
                       t))
                    ((symbol-function 'herdr-agent-prompt)
                     (lambda (target text)
                       (push (list target text) prompts))))
            (with-current-buffer dired-buffer
              (setq selected (list first second))
              (should (limen-herdr-push-context agent))
              (should (= (length published) 1))
              (should-not prompts)
              (setq dired-payload (car published))
              (let* ((payload dired-payload)
                     (items (append (alist-get 'items payload) nil))
                     (serialized (prin1-to-string payload)))
                (should (equal (alist-get 'path payload) first))
                (should (= (alist-get 'line payload) 1))
                (should (= (alist-get 'column payload) 0))
                (should-not (assq 'text payload))
                (should (equal (mapcar (lambda (item)
                                        (list (alist-get 'type item)
                                              (alist-get 'path item)))
                                      items)
                               `(("file" ,first) ("file" ,second))))
                (dolist (item items)
                  (should (equal (alist-get 'type item) "file"))
                  (should (stringp (alist-get 'path item)))
                  (should-not (assq 'text item)))
                (should-not (string-match-p "COPIED-FIRST-CONTENT" serialized))
                (should-not (string-match-p "COPIED-SECOND-CONTENT" serialized)))

              (setq published nil prompts nil
                    selected (list second first))
              (setf (limen-herdr-state-provider state) 'codex)
              (should (limen-herdr-push-context agent))
              (should-not published)
              (should (= (length prompts) 1))
              (let ((text (cadar prompts)))
                (should (= (limen-context-tests--occurrences "second.el" text) 1))
                (should (= (limen-context-tests--occurrences "first.el" text) 1))
                (should-not (string-match-p (regexp-quote root) text))
                (should (< (string-match "second\\.el" text)
                           (string-match "first\\.el" text)))
                (should-not (string-match-p "COPIED-FIRST-CONTENT" text))
                (should-not (string-match-p "COPIED-SECOND-CONTENT" text)))

              (let* ((claude-state
                      (make-limen-claude-state
                       :session integration :client-generation 1))
                     (client
                      (make-limen-claude-client
                       :raw 'raw :open-p t :initialized-p t
                       :generation 1 :state claude-state))
                     (payload dired-payload)
                     notifications)
                (setf (limen-claude-state-current-client claude-state) client)
                (cl-letf (((symbol-function 'limen-claude--notify)
                           (lambda (actual-client method params)
                             (push (list actual-client method params)
                                   notifications))))
                  (limen-claude--integration-event
                   claude-state integration "context.push" payload))
                (should (= (length notifications) 1))
                (pcase-let ((`(,actual-client ,method ,params)
                             (car notifications)))
                  (should (eq actual-client client))
                  (should (equal method "at_mentioned"))
                  (should (equal (limen-context-tests--object-keys params)
                                 '("filePath" "lineEnd" "lineStart")))
                  (should (equal (alist-get 'filePath params) first))
                  (should (= (alist-get 'lineStart params) 1))
                  (should (equal (alist-get 'lineEnd params) 1))
                  (let ((serialized (prin1-to-string params)))
                    (should (= (limen-context-tests--occurrences
                                first serialized)
                               1))
                    (should-not (string-match-p
                                 (regexp-quote second) serialized)))))

              (setf (limen-herdr-state-provider state) 'pi)
              (setq prompts nil published nil)
              (dired-unmark-all-marks)
              (should (dired-goto-file first))
              (should (equal (dired-get-filename nil t) first))
              (setq selected real-selection)
              (should-error (limen-herdr-push-context agent)
                            :type 'user-error)
              (should-not published)
              (should-not prompts)

              (dolist (case
                       `((directory (,first ,directory) nil)
                         (symlink (,first ,symlink) nil)
                         (unreadable (,first ,unreadable) nil)
                         (outside (,first ,outside) nil)
                         (denied (,first ,denied) ("\\`denied\\.el\\'"))
                         (item-cap ,cap-files nil)))
                (pcase-let ((`(,label ,files ,deny-regexps) case))
                  (setq selected files)
                  (let ((limen-project-path-deny-regexps deny-regexps))
                    (ert-info ((format "invalid Dired selection=%s" label))
                      (should-error (limen-herdr-push-context agent)
                                    :type 'user-error)))
                  (should-not published)
                  (should-not prompts)))
              (should (= (length dired-calls) 9))
              (dolist (call dired-calls)
                (should (equal call '(nil marked nil)))))))
      (when (buffer-live-p dired-buffer)
        (kill-buffer dired-buffer))
      (unless (limen-session-closed-p integration)
        (limen-close-session integration))
      (delete-directory root t)
      (delete-directory outside-root t))))

(provide 'limen-context-tests)
;;; limen-context-tests.el ends here
