;;; limen-inbox-tests.el --- Inbox dashboard tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'herdr-status)
(require 'herdr-status-tests)
(require 'limen-inbox)

(defun limen-inbox-tests--ask (pane id)
  (limen-inbox--on-event
   "claude"
   `((hook_event_name . "PreToolUse") (session_id . ,(concat "agent-" pane))
     (server . "/tmp/alpha.sock") (pane . ,pane)
     (tool_name . "AskUserQuestion") (tool_use_id . ,id)
     (tool_input
      . ((questions . [((question . "Which database?") (header . "Database")
                        (options . [((label . "PostgreSQL")) ((label . "MongoDB"))])
                        (multiSelect . :false))]))))
   nil nil))

(ert-deftest limen-inbox-section-lists-pending-questions-and-hides-when-empty ()
  (let ((limen-inbox--questions nil)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh nil))
    (herdr-status-tests--with-dashboard
      (should-not (re-search-forward "^Inbox" nil t))
      (limen-inbox-tests--ask "%1" "t1")
      (limen-inbox-tests--ask "%9" "t2")
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (goto-char (point-min))
      (should (looking-at "Inbox 1"))
      (forward-line 1)
      (should (looking-at " +. +api-review +. +claude"))
      (should (equal (herdr-status-target-at-point) '("/tmp/alpha.sock" . "t1")))
      (forward-line 1)
      (should (looking-at "    Database: Which database\\?$"))
      (forward-line 1)
      (should (looking-at "      PostgreSQL · MongoDB$"))
      (forward-line 1)
      (should (looking-at "Recent\\|Agents"))
      (should (equal (mapcar (lambda (entry) (alist-get 'id entry))
                             (limen-inbox-questions))
                     '("t1")))
      (limen-inbox--on-event
       "claude"
       '((hook_event_name . "PostToolUse") (session_id . "agent-%1")
         (tool_name . "AskUserQuestion") (tool_use_id . "t1"))
       nil nil)
      (herdr-status-refresh)
      (goto-char (point-min))
      (should-not (re-search-forward "^Inbox" nil t)))))

(defun limen-inbox-tests--ask-multi (pane id)
  (limen-inbox--on-event
   "claude"
   `((hook_event_name . "PreToolUse") (session_id . ,(concat "agent-" pane))
     (server . "/tmp/alpha.sock") (pane . ,pane)
     (tool_name . "AskUserQuestion") (tool_use_id . ,id)
     (tool_input
      . ((questions . [((question . "Include tests?") (header . "Scope")
                        (options . [((label . "Yes")) ((label . "No"))])
                        (multiSelect . t))]))))
   nil nil))

(ert-deftest limen-inbox-section-renders-options-as-lines-when-enabled ()
  (let ((limen-inbox--questions nil)
        (limen-inbox-answer t)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh nil))
    (clrhash limen-inbox--selected)
    (herdr-status-tests--with-dashboard
      (limen-inbox-tests--ask "%1" "t1")
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (goto-char (point-min))
      (should-not (re-search-forward "PostgreSQL · MongoDB" nil t))
      (goto-char (point-min))
      (should (re-search-forward "^      1[.] ○ PostgreSQL$" nil t))
      (goto-char (match-beginning 0))
      (let ((section (magit-current-section)))
        (should (eq (oref section type) 'limen-inbox-option))
        (should (equal (plist-get (oref section value) :label) "PostgreSQL"))
        (should (equal (plist-get (limen-inbox--value 'limen-inbox-question) :target)
                       '("/tmp/alpha.sock" . "t1")))))))

(ert-deftest limen-inbox-section-toggles-multi-select-with-circles ()
  (let ((limen-inbox--questions nil)
        (limen-inbox-answer t)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh nil))
    (clrhash limen-inbox--selected)
    (herdr-status-tests--with-dashboard
      (limen-inbox-tests--ask-multi "%1" "m1")
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (goto-char (point-min))
      (should (re-search-forward "^      1[.] ○ Yes$" nil t))
      (goto-char (point-min))
      (should-not (re-search-forward "↵ send" nil t))
      (goto-char (point-min))
      (re-search-forward "^      1[.] ○ Yes$")
      (goto-char (match-beginning 0))
      (limen-inbox-toggle-at-point)
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (goto-char (point-min))
      (should (re-search-forward "^      1[.] ● Yes$" nil t))
      (goto-char (point-min))
      (should-not (re-search-forward "↵ send" nil t)))))

(ert-deftest limen-inbox-section-recommit-updates-markers-and-advances ()
  (let ((limen-inbox--questions nil)
        (limen-inbox--selected (make-hash-table :test 'equal))
        (limen-inbox--sent (make-hash-table :test 'equal))
        (limen-inbox--tabs (make-hash-table :test 'equal))
        (limen-inbox-key-delay 0)
        (limen-inbox-answer t)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh nil)
        sent)
    (herdr-status-tests--with-dashboard
      (limen-inbox-tests--ask-multi "%1" "m1")
      (let* ((entry (car limen-inbox--questions))
             (second (copy-tree (car (alist-get 'questions entry)))))
        (setf (alist-get 'qid second) "m1#1"
              (alist-get 'header second) "Next"
              (alist-get 'questions entry)
              (append (alist-get 'questions entry) (list second))))
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (goto-char (point-min))
      (re-search-forward "^    Scope:")
      (beginning-of-line)
      (let ((last-command-event ?1)) (limen-inbox-toggle-index))
      (let ((last-command-event ?2)) (limen-inbox-toggle-index))
      (should (equal (gethash "m1#0" limen-inbox--selected) '("Yes" "No")))
      (cl-letf (((symbol-function 'herdr-agent-send-keys)
                 (lambda (_target keys) (setq sent (append sent keys))))
                ((symbol-function 'limen-inbox--refresh)
                 (lambda () (herdr-status-refresh) (herdr-status-tests--expand))))
        (limen-inbox-commit-at-point)
        (should (equal sent '("1" "2" "right")))
        (should (equal (plist-get (limen-inbox--value 'limen-inbox-question) :qid)
                       "m1#1"))
        (goto-char (point-min))
        (should (re-search-forward "Scope:.*✓ sent" nil t))
        (beginning-of-line)
        (let ((last-command-event ?1)) (limen-inbox-toggle-index))
        (goto-char (point-min))
        (should (re-search-forward "Scope:.*changed" nil t))
        (beginning-of-line)
        (setq sent nil)
        (limen-inbox-commit-at-point)
        (should (equal sent '("left" "1" "right")))
        (should (equal (plist-get (limen-inbox--value 'limen-inbox-question) :qid)
                       "m1#1"))))))

(ert-deftest limen-inbox-section-keys-work-on-heading-and-option-body ()
  (let ((limen-inbox--questions nil)
        (limen-inbox--selected (make-hash-table :test 'equal))
        (limen-inbox--sent (make-hash-table :test 'equal))
        (limen-inbox--tabs (make-hash-table :test 'equal))
        (limen-inbox-key-delay 0)
        (limen-inbox-answer t)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh nil)
        sent)
    (herdr-status-tests--with-dashboard
      (limen-inbox-tests--ask-multi "%1" "m1")
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (dolist (pattern '("^    Scope:" "^      1[.] ○ Yes" "^      2[.] ○ No"))
        (goto-char (point-min))
        (re-search-forward pattern)
        (dolist (position (list (line-beginning-position) (1- (point))
                               (line-end-position)))
          (goto-char position)
          (should (eq (key-binding (kbd "C-c C-c"))
                      #'limen-inbox-commit-at-point))
          (should (eq (key-binding (kbd "C-c C-d"))
                      #'limen-inbox-dismiss-at-point))
          (should (eq (key-binding (kbd "1")) #'limen-inbox-toggle-index))
          (should (eq (key-binding (kbd "2")) #'limen-inbox-toggle-index))))
      (goto-char (point-min))
      (re-search-forward "^      1[.] ○ Yes")
      (backward-char)
      (let ((last-command-event ?2))
        (call-interactively (key-binding (kbd "2"))))
      (should (equal (gethash "m1#0" limen-inbox--selected) '("No")))
      (should (eq (key-binding (kbd "RET")) #'limen-inbox-toggle-at-point))
      (should (eq (key-binding (kbd "SPC")) #'limen-inbox-toggle-at-point))
      (cl-letf (((symbol-function 'herdr-agent-send-keys)
                 (lambda (_target keys) (setq sent (append sent keys))))
                ((symbol-function 'y-or-n-p) (lambda (_) nil)))
        (call-interactively (key-binding (kbd "C-c C-c"))))
      (should (equal sent '("2" "right"))))))

(ert-deftest limen-inbox-question-title-return-attaches-without-answering ()
  (let ((limen-inbox--questions nil)
        (limen-inbox-answer t)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh nil)
        attached)
    (herdr-status-tests--with-dashboard
      (limen-inbox-tests--ask "%1" "t1")
      (herdr-status-refresh)
      (herdr-status-tests--expand)
      (goto-char (point-min))
      (re-search-forward "^    Database:")
      (should (eq (key-binding (kbd "RET")) #'limen-inbox-attach-at-point))
      (cl-letf (((symbol-function 'herdr-agent-switch)
                 (lambda (target) (setq attached target)))
                ((symbol-function 'herdr-agent-send-keys)
                 (lambda (&rest _) (ert-fail "Attaching must not send answer keys"))))
        (call-interactively (key-binding (kbd "RET"))))
      (should (equal attached '("/tmp/alpha.sock" . "t1")))
      (should (limen-inbox-questions))
      (re-search-forward "^      1[.] ○ PostgreSQL")
      (should (eq (key-binding (kbd "RET")) #'limen-inbox-toggle-at-point)))))

(provide 'limen-inbox-integration-tests)
;;; limen-inbox-tests.el ends here

(ert-deftest limen-inbox-question-shows-at-once-from-the-cached-dashboard ()
  (let ((limen-inbox--questions nil)
        (herdr-status-sections-functions '(limen-inbox--insert-section))
        (herdr-status-auto-refresh t)
        (herdr-status--timer nil)
        (fetches 0))
    (herdr-status-tests--with-dashboard
      (unwind-protect
          (cl-letf* ((collect (symbol-function 'herdr-status--collect-entries))
                     ((symbol-function 'herdr-status--collect-entries)
                      (lambda () (cl-incf fetches) (funcall collect))))
            (should-not (re-search-forward "^Inbox" nil t))
            (limen-inbox-tests--ask "%1" "t1")
            (goto-char (point-min))
            (should (re-search-forward "^Inbox 1" nil t))
            (should (= fetches 0))
            (should-not herdr-status--timer)
            (limen-inbox-tests--ask "%9" "t2")
            (should (timerp herdr-status--timer))
            (should (= fetches 0))
            (should (equal (mapcar (lambda (entry) (alist-get 'id entry))
                                   (limen-inbox-questions))
                           '("t1" "t2")))
            (goto-char (point-min))
            (should (re-search-forward "^Inbox 1" nil t)))
        (when herdr-status--timer
          (cancel-timer herdr-status--timer)
          (setq herdr-status--timer nil))))))
