;;; limen-message-tests.el --- Composer context integration tests -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'herdr-agent)
(require 'cera)
(require 'limen-message)

(defun limen-message-integration--display-text ()
  "Return temporary display strings around the active composer."
  (mapconcat
   (lambda (overlay)
     (mapconcat (lambda (property)
                  (let ((value (overlay-get overlay property)))
                    (if (stringp value) (substring-no-properties value) "")))
                '(before-string after-string display) ""))
   (overlays-in (point-min) (point-max)) "\n"))

(ert-deftest limen-message-integration-keeps-context-out-of-the-outgoing-draft ()
  (let* ((limen-message-context t)
         (limen-message-summary nil)
         (herdr-message-show-agent nil)
         (herdr-message-history nil)
         (herdr-message-compose-functions nil)
         (target '("/tmp/limen-message.sock" . "terminal-1"))
         (session (herdr-agent--make-session
                   :kind "claude" :terminal "terminal-1" :server (car target)
                   :agent-session '((kind . "id") (value . "conversation-1"))))
         (reply (concat "LATEST_REPLY: the change is ready.\n"
                        (mapconcat (lambda (index) (format "Detail line %d" index))
                                   (number-sequence 1 12) "\n")
                        "\nFULL_REPLY_TAIL"))
         (records `(((doc_id . "user-1") (role . "user") (turn_id . 1)
                     (text . "Please make the change"))
                    ((doc_id . "reply-1") (role . "assistant") (turn_id . 1)
                     (text . ,reply))))
         (original-require (symbol-function 'require))
         callbacks timers sent)
    (unwind-protect
        (progn
          (limen-message-enable)
          (save-window-excursion
            (with-temp-buffer
              (text-mode)
              (set-window-buffer (selected-window) (current-buffer))
              (insert "source line\nnext line\n")
              (goto-char (point-min))
              (let ((before (buffer-string))
                    (original-toggle (key-binding (kbd "C-c C-v")))
                    (margins-before (window-margins)))
                (cl-letf (((symbol-function 'require)
                           (lambda (feature &rest arguments)
                             (if (memq feature '(memex memex-api memex-herdr memex-entry))
                                 feature
                               (apply original-require feature arguments))))
                          ((symbol-function 'herdr-agent-find) (lambda (&rest _) session))
                          ((symbol-function 'herdr-message--target-label) (lambda (_) "Test agent"))
                          ((symbol-function 'herdr-message--field-prefix) (lambda (_) "*"))
                          ((symbol-function 'herdr-agent-prompt)
                           (lambda (actual text) (push (list actual text) sent)))
                          ((symbol-function 'memex-api-index)
                           (lambda (callback &rest _)
                             (push (lambda () (funcall callback '((files_scanned . 0))))
                                   callbacks)
                             nil))
                          ((symbol-function 'memex-api-sessions)
                           (lambda (callback &rest _)
                             (push (lambda ()
                                     (funcall callback
                                              '(((session_id . "conversation-1")
                                                 (source_path . "/indexed/conversation.jsonl")
                                                 (source . "claude")
                                                 (message_count . 999)))))
                                   callbacks)
                             nil))
                          ((symbol-function 'memex-api-session-page)
                           (lambda (id path callback &rest options)
                             (should (equal id "conversation-1"))
                             (should (equal path "/indexed/conversation.jsonl"))
                             (let* ((offset (or (plist-get options :offset) 0))
                                    (limit (or (plist-get options :limit) 32))
                                    (page (seq-subseq records offset
                                                      (min (length records) (+ offset limit)))))
                               (push (lambda ()
                                       (funcall callback
                                                `((session_id . ,id) (source_path . ,path)
                                                  (total . ,(length records)) (offset . ,offset)
                                                  (records . ,page))))
                                     callbacks))
                             nil))
                          ((symbol-function 'memex-cancel-rpc) #'ignore)
                          ((symbol-function 'run-at-time)
                           (lambda (delay _repeat function &rest arguments)
                             (let ((timer (timer-create)))
                               (when (and (numberp delay) (zerop delay))
                                 (push (lambda () (apply function arguments)) callbacks))
                               (push timer timers)
                               timer)))
                          ((symbol-function 'exit-recursive-edit) #'ignore)
                          ((symbol-function 'recursive-edit)
                           (lambda ()
                             (insert "My draft")
                             (let ((text (buffer-string))
                                   (position (point))
                                   (undo (copy-tree buffer-undo-list))
                                   (turns 0))
                               (while (and callbacks (< turns 20))
                                 (cl-incf turns)
                                 (funcall (pop callbacks)))
                               (should-not callbacks)
                               (should (eq (key-binding (kbd "C-c C-v"))
                                           #'limen-message-toggle))
                               (should (string-match-p "LATEST_REPLY"
                                                       (limen-message-integration--display-text)))
                               (let ((keys (copy-sequence (kbd "C-c C-v")))
                                     (command nil))
                                 (setq command (key-binding keys))
                                 (should command)
                                 (call-interactively command))
                               (should (string-match-p "FULL_REPLY_TAIL"
                                                       (limen-message-integration--display-text)))
                               (should (= (point) position))
                               (should (equal (buffer-string) text))
                               (should (equal buffer-undo-list undo)))
                             (cera-accept))))
                  (herdr-message-read-field target "file: source.el:1\nsource line"))
                (should (equal (buffer-string) before))
                (should (eq (key-binding (kbd "C-c C-v")) original-toggle))
                (should (equal (window-margins) margins-before))))))
      (limen-message-disable)
      (mapc #'cancel-timer timers))
    (should (equal sent `((,target "My draft\n\n---\nfile: source.el:1\nsource line"))))
    (should (equal herdr-message-history '("My draft")))))

(ert-deftest limen-message-integration-disabled-does-not-probe-context ()
  (let ((limen-message-context nil)
        (limen-message-summary t)
        (herdr-message-show-agent nil)
        (herdr-message-history nil)
        (herdr-message-compose-functions nil)
        (original-require (symbol-function 'require))
        dependencies sent)
    (unwind-protect
        (progn
          (limen-message-enable)
          (save-window-excursion
            (with-temp-buffer
              (text-mode)
              (set-window-buffer (selected-window) (current-buffer))
              (insert "source\n")
              (goto-char (point-min))
              (let ((original-toggle (key-binding (kbd "C-c C-v"))))
                (cl-letf (((symbol-function 'require)
                           (lambda (feature &rest arguments)
                             (when (string-prefix-p "memex" (symbol-name feature))
                               (push feature dependencies))
                             (apply original-require feature arguments)))
                          ((symbol-function 'herdr-message--target-label) (lambda (_) "Test agent"))
                          ((symbol-function 'herdr-message--field-prefix) (lambda (_) "*"))
                          ((symbol-function 'herdr-agent-prompt)
                           (lambda (_target text) (push text sent)))
                          ((symbol-function 'exit-recursive-edit) #'ignore)
                          ((symbol-function 'recursive-edit)
                           (lambda ()
                             (should (eq (key-binding (kbd "C-c C-v")) original-toggle))
                             (should-not (string-match-p "Latest reply\\|Generated recap"
                                                         (limen-message-integration--display-text)))
                             (insert "Plain draft")
                             (cera-accept))))
                  (herdr-message-read-field '("/tmp/message.sock" . "t1") nil)))
              (should (equal (buffer-string) "source\n")))))
      (limen-message-disable))
    (should-not dependencies)
    (should (equal sent '("Plain draft")))))

(ert-deftest limen-message-integration-context-panes-follow-available-content ()
  (let ((limen-message-context t)
        (limen-message-summary t)
        (herdr-message-show-agent nil)
        (herdr-message-history nil)
        (herdr-message-compose-functions nil)
        timers)
    (unwind-protect
        (progn
          (limen-message-enable)
          (save-window-excursion
            (with-temp-buffer
              (text-mode)
              (set-window-buffer (selected-window) (current-buffer))
              (insert "source\n")
              (goto-char (point-min))
              (let ((margins (window-margins)))
                (cl-letf (((symbol-function 'herdr-message--target-label) (lambda (_) "Test agent"))
                          ((symbol-function 'herdr-message--field-prefix) (lambda (_) "*"))
                          ((symbol-function 'herdr-agent-prompt) #'ignore)
                          ((symbol-function 'run-at-time)
                           (lambda (&rest _) (let ((timer (timer-create)))
                                             (push timer timers) timer)))
                          ((symbol-function 'exit-recursive-edit) #'ignore)
                          ((symbol-function 'recursive-edit)
                           (lambda ()
                             (insert "draft")
                             (let ((text (buffer-string)) (position (point))
                                   (undo (copy-tree buffer-undo-list))
                                   (state limen-message--active))
                               (should (equal (window-margins) margins))
                               (should-not (string-match-p
                                            (concat "LATEST\\|" limen-message-rule)
                                            (limen-message-integration--display-text)))
                               (should-not (commandp (key-binding (kbd "C-c C-v"))))
                               (limen-message--set-latest state "A reply")
                               (limen-message--set-recap state "**Summary**")
                               (let ((shown (limen-message-integration--display-text)))
                                 (should (string-match-p "Summary" shown))
                                 (should (string-match-p "A reply" shown))
                                 (should (< (string-match "Summary" shown)
                                            (string-match "A reply" shown)))
                                 (dolist (row (split-string shown "\n" t))
                                   (should-not (string-match-p "[╭╰│╮╯]" row))
                                   (when (string-match-p "A reply" row)
                                     (should (string-prefix-p limen-message-rule row)))))
                               (should (equal (window-margins) margins))
                               (limen-message--set-recap state nil)
                               (should-not (string-match-p "Summary"
                                                           (limen-message-integration--display-text)))
                               (should (string-match-p "A reply" (limen-message-integration--display-text)))
                               (limen-message--unavailable state)
                               (should-not (string-match-p
                                            "A reply\\|Summary"
                                            (limen-message-integration--display-text)))
                               (should (equal (window-margins) margins))
                               (should (equal (buffer-string) text))
                               (should (= (point) position))
                               (should (equal buffer-undo-list undo)))
                             (cera-accept))))
                  (herdr-message-read-field '("/tmp/message.sock" . "t1") nil))))))
      (limen-message-disable)
      (mapc #'cancel-timer timers))))

(ert-deftest limen-message-integration-field-reopens-holding-its-draft ()
  (let* ((limen-message-context t)
         (limen-message-summary nil)
         (limen-message--drafts (make-hash-table :test #'equal))
         (herdr-message-show-agent nil)
         (herdr-message-history nil)
         (herdr-message-compose-functions nil)
         (target '("/tmp/limen-message.sock" . "terminal-1"))
         timers sent)
    (unwind-protect
        (progn
          (limen-message-enable)
          (save-window-excursion
            (with-temp-buffer
              (text-mode)
              (set-window-buffer (selected-window) (current-buffer))
              (insert "source line\n")
              (goto-char (point-min))
              (cl-letf (((symbol-function 'herdr-message--target-label) (lambda (_) "Test agent"))
                        ((symbol-function 'herdr-message--field-prefix) (lambda (_) "*"))
                        ((symbol-function 'herdr-agent-find) (lambda (&rest _) nil))
                        ((symbol-function 'herdr-agent-prompt)
                         (lambda (_target text) (push text sent)))
                        ((symbol-function 'run-at-time)
                         (lambda (&rest _) (let ((timer (timer-create)))
                                             (push timer timers) timer)))
                        ((symbol-function 'exit-recursive-edit) #'ignore))
                ;; Written, then put away rather than sent.
                (cl-letf (((symbol-function 'recursive-edit)
                           (lambda () (insert "half a message")
                             (limen-message--dismiss))))
                  (should (eq (condition-case nil
                                  (progn (herdr-message-read-field target nil) 'returned)
                                (quit 'quit))
                              'quit)))
                (should (equal (gethash target limen-message--drafts) "half a message"))
                (should (equal (buffer-string) "source line\n"))
                ;; Opened again, the field holds what was left in it.
                (cl-letf (((symbol-function 'recursive-edit)
                           (lambda ()
                             (should (equal (cera-input-text) "half a message"))
                             (insert " finished")
                             (cera-accept))))
                  (herdr-message-read-field target nil))
                (should (equal sent '("half a message finished")))
                (should-not (gethash target limen-message--drafts))
                (should (equal (buffer-string) "source line\n"))))))
      (limen-message-disable)
      (mapc #'cancel-timer timers))))

(provide 'limen-message-integration-tests)
;;; limen-message-tests.el ends here
